<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">  

  <xacro:macro name="barrel" params="prefix parent dir">
    <joint name="${prefix}_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${prefix}_link"/>
      <origin rpy="${pi/2} 0 ${dir}" xyz="${0.014*cos(dir)} ${0.014*sin(dir)} 0.006"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.001"/>
    </joint>

    <link name="${prefix}_link">
      <visual>
        <geometry>
          <mesh filename="package://srs004host/urdf/barrel.stl" />
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://srs004host/urdf/barrel.stl" />
        </geometry>
      </collision>
      <inertial>
        <mass value="0.001"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>  
    </link>

    <joint name="${prefix}_mark_joint" type="fixed">
      <parent link="${prefix}_link"/>
      <child link="${prefix}_mark_link"/>
      <origin rpy="0 0 0" xyz="0.005 0 0"/>
    </joint>
    <link name="${prefix}_mark_link">
      <visual>
        <geometry>
          <box size="0.005 0.005 0.005"/>
        </geometry>
        <material name="white"/>
      </visual>
      <inertial>
        <mass value="0.001"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>  
    </link>


    <!-- ===============  Gazebo =============== -->
    <gazebo reference="${prefix}_link">
      <mu1 value="3.0" />
      <mu2 value="3.0" />
      <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="${prefix}_mark_link">
      <material>Gazebo/White</material>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="omni_wheel" params="prefix parent radius dir height">
    <joint name="${prefix}_motor_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}_motor_link"/>
      <origin rpy="0 ${pi/2} ${dir}" xyz="${radius*cos(dir)} ${radius*sin(dir)} ${height}"/>
    </joint>
 
    <link name="${prefix}_motor_link">
      <visual>
        <geometry>
          <mesh filename="package://srs004host/urdf/motor.stl" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="gray"/>
      </visual>
      <inertial>
        <mass value="0.180"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="${prefix}_housing_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${prefix}_housing_link"/>
      <origin rpy="0 ${pi/2} ${dir}" xyz="${(radius+0.0222)*cos(dir)} ${(radius+0.0222)*sin(dir)} ${height}"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.1"/>
    </joint>
 
    <link name="${prefix}_housing_link">
      <visual>
        <geometry>
          <mesh filename="package://srs004host/urdf/housing.stl" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="gray"/>
      </visual>
      <inertial>
        <mass value="0.009"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>  
    </link>

    <joint name="${prefix}_housing_s_joint" type="fixed">
      <parent link="${prefix}_housing_link"/>
      <child link="${prefix}_housing_s_link"/>
      <origin rpy="0 ${pi} ${pi/4}" xyz="0 0 0"/>
    </joint>

    <link name="${prefix}_housing_s_link">
      <inertial>
        <mass value="0.001"/>
        <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0.00001"/>
      </inertial>  
    </link>

    <xacro:barrel prefix="${prefix}_barrel_1" parent="${prefix}_housing_link" dir="0"/>
    <xacro:barrel prefix="${prefix}_barrel_2" parent="${prefix}_housing_link" dir="${pi/2}"/>
    <xacro:barrel prefix="${prefix}_barrel_3" parent="${prefix}_housing_link" dir="${pi}"/>
    <xacro:barrel prefix="${prefix}_barrel_4" parent="${prefix}_housing_link" dir="${-pi/2}"/>
    <xacro:barrel prefix="${prefix}_barrel_5" parent="${prefix}_housing_s_link" dir="0"/>
    <xacro:barrel prefix="${prefix}_barrel_6" parent="${prefix}_housing_s_link" dir="${pi/2}"/>
    <xacro:barrel prefix="${prefix}_barrel_7" parent="${prefix}_housing_s_link" dir="${pi}"/>
    <xacro:barrel prefix="${prefix}_barrel_8" parent="${prefix}_housing_s_link" dir="${-pi/2}"/>

    <!-- ===============  Transmission =============== -->
    <transmission name="${prefix}_housing_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_housing_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_housing_motor">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>30</mechanicalReduction>
      </actuator>
    </transmission>

    <!-- ===============  Gazebo =============== -->
    <gazebo reference="${prefix}_housing_link">
      <mu1 value="0.8" />
      <mu2 value="0.8" />
      <material>Gazebo/Gray</material>
    </gazebo>
    <gazebo reference="${prefix}_motor_link">
      <mu1 value="0.8" />
      <mu2 value="0.8" />
      <material>Gazebo/Gray</material>
    </gazebo>
  </xacro:macro>
</robot>

